# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ActiveFire
                                 A QGIS plugin
 Active Fire Data within 24 hours (MODIS)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-28
        copyright            : (C) 2020 by The Map Workshop
        email                : themapworkshop@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ActiveFire class from file ActiveFire.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .active_fire import ActiveFire
    return ActiveFire(iface)
